
DROP SCHEMA IF EXISTS `division_politica` ;
CREATE SCHEMA IF NOT EXISTS `division_politica`
	DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci ;
USE `division_politica` ;

DROP TABLE IF EXISTS `division_politica`.`division` ;
CREATE TABLE IF NOT EXISTS `division_politica`.`division` (
  `provincia` INT NOT NULL,
  `canton` INT NOT NULL,
  `distrito` INT NOT NULL,
  `seq_distrito` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`provincia`, `canton`, `distrito`))
ENGINE = InnoDB;
select nombre from division_politica.division;
select provincia,canton,distrito,seq_distrito,nombre from division_politica.division;
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,0,0,0,"San José"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,1,0,0,"San José"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,1,1,1,"Carmen"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,1,2,2,"Merced"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,1,3,3,"Hospital"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,1,4,4,"Catedral"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,1,5,5,"Zapote"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,1,6,6,"San Francisco de Dos Ríos"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,1,7,7,"Uruca"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,1,8,8,"Mata Redonda"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,1,9,9,"Pavas"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,1,10,10,"Hatillo"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,1,11,11,"San Sebastián"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,2,11,11,"Escazú"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,2,12,1,"Escazú"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,2,13,2,"San Antonio"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,2,14,3,"San Rafael"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,3,14,3,"Desamparados"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,3,15,1,"Desamparados"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,3,16,2,"San Miguel"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,3,17,3,"San Juan de Dios"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,3,18,4,"San Rafael Arriba"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,3,19,5,"San Antonio"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,3,20,6,"Frailes"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,3,21,7,"Patarrá"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,3,22,8,"San Cristóbal"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,3,23,9,"Rosario"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,3,24,10,"Damas"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,3,25,11,"San Rafael Abajo"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,3,26,12,"Gravilias"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,3,27,13,"Los Guido"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,4,27,13,"Puriscal"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,4,28,1,"Santiago"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,4,29,2,"Mercedes Sur"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,4,30,3,"Barbacoas"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,4,31,4,"Grifo Alto"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,4,32,5,"San Rafael"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,4,33,6,"Candelarita"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,4,34,7,"Desamparaditos"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,4,35,8,"San Antonio"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,4,36,9,"Chires"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,4,37,10,"La Cangreja"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,5,37,10,"Tarrazú"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,5,38,1,"San Marcos"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,5,39,2,"San Lorenzo"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,5,40,3,"San Carlos"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,6,40,3,"Aserrí"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,6,41,1,"Aserrí"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,6,42,2,"Tarbaca"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,6,43,3,"Vuelta de Jorco"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,6,44,4,"San Gabriel"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,6,45,5,"Legua"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,6,46,6,"Monterrey"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,6,47,7,"Salitrillos"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,7,47,7,"Mora"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,7,48,1,"Ciudad Colón"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,7,49,2,"Guayabo"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,7,50,3,"Tabarcia"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,7,51,4,"Piedras Negras"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,7,52,5,"Picagres"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,7,53,6,"Jaris"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,7,54,7,"Quitirrisí"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,8,54,7,"Goicoechea"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,8,55,1,"Guadalupe"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,8,56,2,"San Francisco"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,8,57,3,"Calle Blancos"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,8,58,4,"Mata de Plátano"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,8,59,5,"Ipís"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,8,60,6,"Rancho Redondo"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,8,61,7,"Purral"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,9,61,7,"Santa Ana"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,9,62,1,"Santa Ana"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,9,63,2,"Salitral"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,9,64,3,"Pozos"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,9,65,4,"Uruca"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,9,66,5,"Piedades"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,9,67,6,"Brasil"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,10,67,6,"Alajuelita"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,10,68,1,"Alajuelita"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,10,69,2,"San Josecito"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,10,70,3,"San Antonio"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,10,71,4,"Concepción"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,10,72,5,"San Felipe"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,11,72,5,"Vázquez de Coronado"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,11,73,1,"San Isidro"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,11,74,2,"San Rafael"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,11,75,3,"Dulce Nombre de Jesús"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,11,76,4,"Patalillo"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,11,77,5,"Cascajal"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,12,77,5,"Acosta"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,12,78,1,"San Ignacio"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,12,79,2,"Guaitil"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,12,80,3,"Palmichal"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,12,81,4,"Cangrejal"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,12,82,5,"Sabanillas"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,13,82,5,"Tibás"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,13,83,1,"San Juan"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,13,84,2,"Cinco Esquinas"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,13,85,3,"Anselmo Llorente"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,13,86,4,"León XIII"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,13,87,5,"Colima"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,14,87,5,"Moravia"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,14,88,1,"San Vicente"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,14,89,2,"San Jerónimo"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,14,90,3,"Trinidad"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,15,90,3,"Montes de Oca"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,15,91,1,"San Pedro"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,15,92,2,"Sabanilla"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,15,93,3,"Mercedes"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,15,94,4,"San Rafael"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,16,94,4,"Turrubares"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,16,95,1,"San Pablo"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,16,96,2,"San Pedro"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,16,97,3,"San Juan de Mata"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,16,98,4,"San Luis"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,16,99,5,"Carara"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,17,99,5,"Dota"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,17,100,1,"Santa María"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,17,101,2,"Jardín"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,17,102,3,"Copey"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,18,102,3,"Curridabat"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,18,103,1,"Curridabat"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,18,104,2,"Granadilla"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,18,105,3,"Sánchez"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,18,106,4,"Tirrases"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,19,106,4,"Pérez Zeledón"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,19,107,1,"San Isidro de El General"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,19,108,2,"El General"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,19,109,3,"Daniel Flores"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,19,110,4,"Rivas"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,19,111,5,"San Pedro"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,19,112,6,"Platanares"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,19,113,7,"Pejibaye"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,19,114,8,"Cajón"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,19,115,9,"Barú"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,19,116,10,"Río Nuevo"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,19,117,11,"Páramo"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,19,118,12,"La Amistad"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,20,118,12,"León Cortés Castro"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,20,119,1,"San Pablo"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,20,120,2,"San Andrés"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,20,121,3,"Llano Bonito"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,20,122,4,"San Isidro"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,20,123,5,"Santa Cruz"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (1,20,124,6,"San Antonio"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,0,0,0,"Alajuela"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,1,0,0,"Alajuela"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,1,1,1,"Alajuela"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,1,2,2,"San José"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,1,3,3,"Carrizal"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,1,4,4,"San Antonio"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,1,5,5,"Guácima"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,1,6,6,"San Isidro"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,1,7,7,"Sabanilla"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,1,8,8,"San Rafael"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,1,9,9,"Río Segundo"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,1,10,10,"Desamparados"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,1,11,11,"Turrúcares"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,1,12,12,"Tambor"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,1,13,13,"Garita"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,1,14,14,"Sarapiquí"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,2,14,14,"San Ramón"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,2,15,1,"San Ramón"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,2,16,2,"Santiago"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,2,17,3,"San Juan"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,2,18,4,"Piedades Norte"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,2,19,5,"Piedades Sur"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,2,20,6,"San Rafael"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,2,21,7,"San Isidro"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,2,22,8,"Ángeles"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,2,23,9,"Alfaro"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,2,24,10,"Volio"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,2,25,11,"Concepción"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,2,26,12,"Zapotal"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,2,27,13,"Peñas Blancas"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,2,28,14,"San Lorenzo"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,3,28,14,"Grecia"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,3,29,1,"Grecia"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,3,30,2,"San Isidro"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,3,31,3,"San José"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,3,32,4,"San Roque"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,3,33,5,"Tacares"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,3,34,6,"Puente de Piedra"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,3,35,7,"Bolívar"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,4,35,7,"San Mateo"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,4,36,1,"San Mateo"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,4,37,2,"Desmonte"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,4,38,3,"Jesús María"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,4,39,4,"Labrador"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,5,39,4,"Atenas"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,5,40,1,"Atenas"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,5,41,2,"Jesús"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,5,42,3,"Mercedes"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,5,43,4,"San Isidro"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,5,44,5,"Concepción"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,5,45,6,"San José"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,5,46,7,"Santa Eulalia"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,5,47,8,"Escobal"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,6,47,8,"Naranjo"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,6,48,1,"Naranjo"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,6,49,2,"San Miguel"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,6,50,3,"San José"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,6,51,4,"Cirrí"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,6,52,5,"San Jerónimo"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,6,53,6,"San Juan"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,6,54,7,"El Rosario"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,6,55,8,"Palmitos"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,7,55,8,"Palmares"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,7,56,1,"Palmares"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,7,57,2,"Zaragoza"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,7,58,3,"Buenos Aires"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,7,59,4,"Santiago"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,7,60,5,"Candelaria"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,7,61,6,"Esquipulas"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,7,62,7,"La Granja"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,8,62,7,"Poás"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,8,63,1,"San Pedro"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,8,64,2,"San Juan"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,8,65,3,"San Rafael"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,8,66,4,"Carrillos"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,8,67,5,"Sabana Redonda"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,9,67,5,"Orotina"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,9,68,1,"Orotina"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,9,69,2,"Mastate"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,9,70,3,"Hacienda Vieja"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,9,71,4,"Coyolar"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,9,72,5,"La Ceiba"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,10,72,5,"San Carlos"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,10,73,1,"Quesada"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,10,74,2,"Florencia"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,10,75,3,"Buenavista"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,10,76,4,"Aguas Zarcas"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,10,77,5,"Venecia"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,10,78,6,"Pital"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,10,79,7,"La Fortuna"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,10,80,8,"La Tigra"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,10,81,9,"La Palmera"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,10,82,10,"Venado"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,10,83,11,"Cutris"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,10,84,12,"Monterrey"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,10,85,13,"Pocosol"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,11,85,13,"Zarcero"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,11,86,1,"Zarcero"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,11,87,2,"Laguna"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,11,88,3,"Tapezco"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,11,89,4,"Guadalupe"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,11,90,5,"Palmira"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,11,91,6,"Zapote"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,11,92,7,"Brisas"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,12,92,7,"Valverde Vega"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,12,93,1,"Sarchí Norte"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,12,94,2,"Sarchí Sur"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,12,95,3,"Toro Amarillo"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,12,96,4,"San Pedro"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,12,97,5,"Rodríguez"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,13,97,5,"Upala"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,13,98,1,"Upala"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,13,99,2,"Aguas Claras"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,13,100,3,"San José (Pizote)"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,13,101,4,"Bijagua"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,13,102,5,"Delicias"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,13,103,6,"Dos Ríos"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,13,104,7,"Yolillal"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,13,105,8,"Canalete"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,14,105,8,"Los Chiles"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,14,106,1,"Los Chiles"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,14,107,2,"Caño Negro"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,14,108,3,"El Amparo"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,14,109,4,"San Jorge"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,15,109,4,"Guatuso"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,15,110,1,"San Rafael"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,15,111,2,"Buenavista"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,15,112,3,"Cote"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,15,113,4,"Katira"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,16,113,4,"Río Cuarto"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,16,114,1,"Río Cuarto"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,16,115,2,"Santa Isabel"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (2,16,116,3,"Santa Rita"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,0,0,0,"Cartago"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,1,0,0,"Cartago"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,1,1,1,"Oriental"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,1,2,2,"Occidental"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,1,3,3,"Carmen"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,1,4,4,"San Nicolás"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,1,5,5,"Agua Caliente (San Francisco)"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,1,6,6,"Guadalupe (Arenilla)"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,1,7,7,"Corralillo"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,1,8,8,"Tierra Blanca"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,1,9,9,"Dulce Nombre"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,1,10,10,"Llano Grande"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,1,11,11,"Quebradilla"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,2,11,11,"Paraíso"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,2,12,1,"Paraíso"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,2,13,2,"Santiago de Paraíso"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,2,14,3,"Orosi"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,2,15,4,"Cachí"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,2,16,5,"Llanos de Santa Lucía"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,3,16,5,"La Unión"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,3,17,1,"Tres Ríos"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,3,18,2,"San Diego"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,3,19,3,"San Juan"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,3,20,4,"San Rafael"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,3,21,5,"Concepción"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,3,22,6,"Dulce Nombre"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,3,23,7,"San Ramón"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,3,24,8,"Río Azul"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,4,24,8,"Jiménez"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,4,25,1,"Juan Viñas"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,4,26,2,"Tucurrique"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,4,27,3,"Pejibaye"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,5,27,3,"Turrialba"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,5,28,1,"Turrialba"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,5,29,2,"La Suiza"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,5,30,3,"Peralta"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,5,31,4,"Santa Cruz"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,5,32,5,"Santa Teresita"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,5,33,6,"Pavones"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,5,34,7,"Tuis"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,5,35,8,"Tayutic"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,5,36,9,"Santa Rosa"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,5,37,10,"Tres Equis"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,5,38,11,"La Isabel"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,5,39,12,"Chirripó"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,6,39,12,"Alvarado"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,6,40,1,"Pacayas"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,6,41,2,"Cervantes"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,6,42,3,"Capellades"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,7,42,3,"Oreamuno"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,7,43,1,"San Rafael"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,7,44,2,"Cot"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,7,45,3,"Potrero Cerrado"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,7,46,4,"Cipreses"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,7,47,5,"Santa Rosa"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,8,47,5,"El Guarco"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,8,48,1,"Tejar"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,8,49,2,"San Isidro"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,8,50,3,"Tobosi"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (3,8,51,4,"Patio de Agua"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,0,0,0,"Heredia"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,1,0,0,"Heredia"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,1,1,1,"Heredia"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,1,2,2,"Mercedes"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,1,3,3,"San Francisco"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,1,4,4,"Ulloa"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,1,5,5,"Vara Blanca"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,2,5,5,"Barva"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,2,6,1,"Barva"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,2,7,2,"San Pedro"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,2,8,3,"San Pablo"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,2,9,4,"San Roque"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,2,10,5,"Santa Lucía"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,2,11,6,"San José de la Montaña"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,3,11,6,"Santo Domingo"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,3,12,1,"Santo Domingo"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,3,13,2,"San Vicente"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,3,14,3,"San Miguel"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,3,15,4,"Paracito"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,3,16,5,"Santo Tomás"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,3,17,6,"Santa Rosa"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,3,18,7,"Tures"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,3,19,8,"Pará"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,4,19,8,"Santa Bárbara"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,4,20,1,"Santa Bárbara"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,4,21,2,"San Pedro"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,4,22,3,"San Juan"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,4,23,4,"Jesús"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,4,24,5,"Santo Domingo"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,4,25,6,"Purabá"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,5,25,6,"San Rafael"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,5,26,1,"San Rafael"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,5,27,2,"San Josecito"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,5,28,3,"Santiago"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,5,29,4,"Ángeles"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,5,30,5,"Concepción"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,6,30,5,"San Isidro"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,6,31,1,"San Isidro"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,6,32,2,"San José"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,6,33,3,"Concepción"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,6,34,4,"San Francisco"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,7,34,4,"Belén"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,7,35,1,"San Antonio"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,7,36,2,"La Ribera"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,7,37,3,"La Asunción"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,8,37,3,"Flores"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,8,38,1,"San Joaquín"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,8,39,2,"Barrantes"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,8,40,3,"Llorente"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,9,40,3,"San Pablo"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,9,41,1,"San Pablo"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,9,42,2,"Rincón de Sabanilla"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,10,42,2,"Sarapiquí"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,10,43,1,"Puerto Viejo"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,10,44,2,"La Virgen"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,10,45,3,"Horquetas"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,10,46,4,"Llanuras del Gaspar"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (4,10,47,5,"Cureña"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,0,0,0,"Guanacaste"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,1,0,0,"Liberia"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,1,1,1,"Liberia"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,1,2,2,"Cañas Dulces"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,1,3,3,"Mayorga"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,1,4,4,"Nacascolo"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,1,5,5,"Curubandé"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,2,5,5,"Nicoya"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,2,6,1,"Nicoya"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,2,7,2,"Mansión"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,2,8,3,"San Antonio"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,2,9,4,"Quebrada Honda"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,2,10,5,"Sámara"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,2,11,6,"Nosara"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,2,12,7,"Belén de Nosarita"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,3,12,7,"Santa Cruz"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,3,13,1,"Santa Cruz"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,3,14,2,"Bolsón"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,3,15,3,"Veintisiete de Abril"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,3,16,4,"Tempate"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,3,17,5,"Cartagena"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,3,18,6,"Cuajiniquil"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,3,19,7,"Diriá"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,3,20,8,"Cabo Velas"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,3,21,9,"Tamarindo"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,4,21,9,"Bagaces"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,4,22,1,"Bagaces"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,4,23,2,"La Fortuna"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,4,24,3,"Mogote"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,4,25,4,"Río Naranjo"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,5,25,4,"Carrillo"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,5,26,1,"Filadelfia"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,5,27,2,"Palmira"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,5,28,3,"Sardinal"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,5,29,4,"Belén"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,6,29,4,"Cañas"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,6,30,1,"Cañas"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,6,31,2,"Palmira"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,6,32,3,"San Miguel"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,6,33,4,"Bebedero"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,6,34,5,"Porozal"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,7,34,5,"Abangares"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,7,35,1,"Las Juntas"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,7,36,2,"Sierra"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,7,37,3,"San Juan"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,7,38,4,"Colorado"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,8,38,4,"Tilarán"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,8,39,1,"Tilarán"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,8,40,2,"Quebrada Grande"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,8,41,3,"Tronadora"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,8,42,4,"Santa Rosa"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,8,43,5,"Líbano"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,8,44,6,"Tierras Morenas"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,8,45,7,"Arenal"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,9,45,7,"Nandayure"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,9,46,1,"Carmona"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,9,47,2,"Santa Rita"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,9,48,3,"Zapotal"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,9,49,4,"San Pablo"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,9,50,5,"Porvenir"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,9,51,6,"Bejuco"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,10,51,6,"La Cruz"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,10,52,1,"La Cruz"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,10,53,2,"Santa Cecilia"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,10,54,3,"La Garita"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,10,55,4,"Santa Elena"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,11,55,4,"Hojancha"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,11,56,1,"Hojancha"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,11,57,2,"Monte Romo"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,11,58,3,"Puerto Carrillo"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,11,59,4,"Huacas"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (5,11,60,5,"Matambú"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,0,0,0,"Puntarenas"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,1,0,0,"Puntarenas"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,1,1,1,"Puntarenas"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,1,2,2,"Pitahaya"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,1,3,3,"Chomes"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,1,4,4,"Lepanto"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,1,5,5,"Paquera"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,1,6,6,"Manzanillo"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,1,7,7,"Guacimal"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,1,8,8,"Barranca"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,1,9,9,"Monteverde"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,1,10,10,"Isla del Coco"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,1,11,11,"Cóbano"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,1,12,12,"Chacarita"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,1,13,13,"Chira"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,1,14,14,"Acapulco"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,1,15,15,"El Roble"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,1,16,16,"Arancibia"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,2,16,16,"Esparza"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,2,17,1,"Espíritu Santo"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,2,18,2,"San Juan Grande"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,2,19,3,"Macacona"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,2,20,4,"San Rafael"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,2,21,5,"San Jerónimo"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,2,22,6,"Caldera"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,3,22,6,"Buenos Aires"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,3,23,1,"Buenos Aires"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,3,24,2,"Volcán"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,3,25,3,"Potrero Grande"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,3,26,4,"Boruca"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,3,27,5,"Pilas"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,3,28,6,"Colinas"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,3,29,7,"Chánguena"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,3,30,8,"Biolley"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,3,31,9,"Brunka"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,4,31,9,"Montes de Oro"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,4,32,1,"Miramar"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,4,33,2,"La Unión"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,4,34,3,"San Isidro"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,5,34,3,"Osa"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,5,35,1,"Cortés"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,5,36,2,"Palmar"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,5,37,3,"Sierpe"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,5,38,4,"Bahía Ballena"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,5,39,5,"Piedras Blancas"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,5,40,6,"Bahía Drake"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,6,40,6,"Quepos"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,6,41,1,"Quepos"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,6,42,2,"Savegre"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,6,43,3,"Naranjito"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,7,43,3,"Golfito"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,7,44,1,"Golfito"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,7,45,2,"Puerto Jiménez"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,7,46,3,"Guaycará"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,7,47,4,"Pavón"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,8,47,4,"Coto Brus"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,8,48,1,"San Vito"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,8,49,2,"Sabalito"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,8,50,3,"Aguabuena"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,8,51,4,"Limoncito"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,8,52,5,"Pittier"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,8,53,6,"Gutiérrez Brown"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,9,53,6,"Parrita"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,9,54,1,"Parrita"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,10,54,1,"Corredores"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,10,55,1,"Corredor"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,10,56,2,"La Cuesta"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,10,57,3,"Paso Canoas"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,10,58,4,"Laurel"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,11,58,4,"Garabito"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,11,59,1,"Jacó"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (6,11,60,2,"Tárcoles"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (7,0,0,0,"Limón"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (7,1,0,0,"Limón"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (7,1,1,1,"Limón"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (7,1,2,2,"Valle La Estrella"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (7,1,3,3,"Río Blanco"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (7,1,4,4,"Matama"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (7,2,4,4,"Pococí"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (7,2,5,1,"Guápiles"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (7,2,6,2,"Jiménez"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (7,2,7,3,"La Rita"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (7,2,8,4,"Roxana"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (7,2,9,5,"Cariari"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (7,2,10,6,"Colorado"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (7,2,11,7,"La Colonia"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (7,3,11,7,"Siquirres"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (7,3,12,1,"Siquirres"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (7,3,13,2,"Pacuarito"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (7,3,14,3,"Florida"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (7,3,15,4,"Germania"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (7,3,16,5,"Cairo"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (7,3,17,6,"Alegría"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (7,4,17,6,"Talamanca"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (7,4,18,1,"Bratsi"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (7,4,19,2,"Sixaola"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (7,4,20,3,"Cahuita"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (7,4,21,4,"Telire"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (7,5,21,4,"Matina"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (7,5,22,1,"Matina"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (7,5,23,2,"Batán"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (7,5,24,3,"Carrandi"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (7,6,24,3,"Guácimo"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (7,6,25,1,"Guácimo"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (7,6,26,2,"Mercedes"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (7,6,27,3,"Pocora"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (7,6,28,4,"Río Jiménez"  );
insert into division_politica.division (provincia ,  canton , distrito , seq_distrito, nombre)  values (7,6,29,5,"Duacarí"  );
